spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/rest-with-spring-boot
        username: admin
        password: admin
        driver-class-name: org.postgresql.Driver
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: update

